
#Example 1================
resource "time_static" "time_update" {
}

resource "local_file" "time" {
  filename = "time.txt"
  content  = "Time stamp of this file is ${time_static.time_update.id}"
}

#Example 2================
resource "tls_private_key" "pvtkey" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "local_file" "key_details" {
  filename = "key.key"
  content  = tls_private_key.pvtkey.private_key_pem
}

#Example 3=====Explicit Dependencies===========
resource "local_file" "whale" {
  filename   = "whale"
  content    = "whale"
  depends_on = [local_file.krill]
}

resource "local_file" "krill" {
  filename = "krill"
  content  = "krill"
}

#Example 4==== Output Values============
resource "random_pet" "my-pet" {

  length = 1
}

output "pet-name" {

  value       = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}

resource "local_file" "welcome" {
  filename = "message.txt"
  content  = "Welcome to Kodekloud."
}

output "welcome_message" {

  value       = local_file.welcome.content
  description = "content of the resource called welcome"
}

#Example 5======= Output Values from Data Sources========
output "os-version" {
  value = data.local_file.os.content
}
data "local_file" "os" {
  filename = "message.txt"
}

#Example 6=======use for_each ========
resource "local_sensitive_file" "name" {
    filename = each.value
    content = var.content
   for_each = toset(var.users)
}
variable "users" {
    type = list(string)
    default = [ "user10", "user11", "user12", "user10"]
}
variable "content" {
    default = "password: S3cr3tP@ssw0rd"
  
}